### PR TITLE
Subseting a record by passing the names of fields

### PR DESCRIPTION
**Pull request by paulvictor**

### CODE REVIEW

**Comment by justinwoo** [comment]
This is usually called "pick", but I think there's already an implementation by @coot? I don't know what quite happened though.

**Comment by justinwoo** [comment]
e.g. https://gist.github.com/coot/3120e715341dbe38b82e6dbf7a987ab7, but I thought there was a library

**Comment by paulvictor** [comment]
Ok, I just wanted such an implementation for one of the applications I'm building and couldn't find one, so the PR. Can it be merged though? Let me know if there's any room for improvement as well.

**Comment by Gerstacker** [comment]
@coot's implementation could lose the first argument (proxy for row type) because the return type has that information (I don't know if that's considered bad practice). The same may be possible with this but again, may not be desirable.

**Comment by coot** [comment]
thanks @Gerstacker indeed it can be dropped. There was some discussion in this [PR](https://github.com/purescript/purescript-record/pull/6), please feel free to use it or make a PR.

**Comment by justinwoo** [comment]
Sorry for not getting to this, but I guess this is now solved by #17

**Pull request closed without merging**
